spring:
  application:
    name: 'customer service'
    boot:
      admin:
        client:
          url: http://localhost:8081
datasource:
url: jdbc:h2:mem:customer
username: sa
password:
driver-class-name: org.h2.Driver
platform: h2
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka